# action.yml
name: 'Code Review with ChatGPT'
description: 'Automating code review using ChatGPT with Github Actions integration on PRs for code explanations.'
inputs:
  openai_api_key: # id of input
    description: 'OpenAI API Key'
    required: true
    default: ''
  github_token: # id of input
    description: 'Github API Key'
    required: true
    default: ''
  github_pr_id: # id of input
    description: 'Github PR ID'
    required: true
    default: ''
  openai_model: # id of input
    description: 'GPT-3 models can understand and generate natural language. Davinci is the most capable model, and Ada is the fastest.'
    required: false
    default: 'gpt-3.5-turbo'
  openai_temperature: # id of input
    description: 'What sampling temperature to use. Higher values means the model will take more risks. Try 0.9 for more creative applications, and 0 (argmax sampling) for ones with a well-defined answer. 0~2'
    required: false
    default: '0.7'
  openai_top_p: # id of input
    description: '0.1 means only the tokens comprising the top 10% probability mass are considered.'
    required: false
    default: '0.8'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.openai_api_key }}
    - ${{ inputs.github_token }}
    - ${{ inputs.github_pr_id }}
    - ${{ inputs.openai_model }}
    - ${{ inputs.openai_temperature }}
    - ${{ inputs.openai_top_p }}
