name: PR Review
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  add-auto-review-comment:
    runs-on: ubuntu-latest
    name: ChatGPT review code
    steps:
      - uses: Jonghakseo/gpt-pr-github-actions@latest # This is example. use Jonghakseo/gpt-pr-github-actions@v1
        with:
          openai_api_key: ${{ secrets.openai_api_key }} # Get the OpenAI API key from repository secrets
          github_token: ${{ secrets.GITHUB_TOKEN }} # Get the Github Token from repository secrets
          github_pr_id: ${{ github.event.number }} # Get the Github Pull Request ID from the Github event
          openai_model: "gpt-3.5-turbo" # Optional: specify the OpenAI engine to use. [gpt-3.5-turbo, text-davinci-002, text-babbage-001, text-curie-001, text-ada-001'] Default is 'gpt-3.5-turbo'
          openai_temperature: 0.7 # Optional: Default is 0.7
          openai_top_p: 0.8 # Optional: Default 0.8